spring:
  datasource:
    url: jdbc:oracle:thin:@//oracle.fiap.com.br:1521/ORCL
    driver-class-name: oracle.jdbc.OracleDriver
    username: rm558303
    password: fiap25

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate 
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration/oracle
    schemas: RM558303       # use UPPERCASE com o nome do schema/usu√°rio Oracle
    baseline-on-migrate: true
    clean-on-validation-error: true
