spring:
  datasource:
    url: jdbc:oracle:thin:@//oracle.fiap.com.br:1521/ORCL
    driver-class-name: oracle.jdbc.OracleDriver
    username: rm558303
    password: fiap25

  jpa:
    hibernate:
      ddl-auto: validate
    properties: {}

  flyway:
    enabled: true
    locations: classpath:db/migration/oracle
    clean-on-validation-error: true
    baseline-on-migrate: true
    baseline-version: 0
    clean-disabled: false
